# Generated by Django 3.1 on 2021-09-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_auto_20210909_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
